// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  recordingId: __t.string().primaryKey().name("recording_id"),
  meetingId: __t.string().name("meeting_id"),
  groupId: __t.u64().name("group_id"),
  status: __t.string(),
  objectKey: __t.string().name("object_key"),
  outputFileName: __t.string().name("output_file_name"),
  startedAtMs: __t.u64().name("started_at_ms"),
  durationSecs: __t.u32().name("duration_secs"),
  spaceFlag: __t.u8().name("space_flag"),
});
