// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  kind: __t.string(),
  name: __t.string(),
  closed: __t.bool(),
  mapId: __t.u32().name("map_id"),
  x: __t.f64(),
  y: __t.f64(),
  w: __t.f64(),
  h: __t.f64(),
});
