// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.7.1 (commit 8ecd3c3bac427a49a9d9b13671bf83324afa59ba).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AnnounceIdleSuspendReducer from "./announce_idle_suspend_reducer";
import ApplyForMembershipReducer from "./apply_for_membership_reducer";
import ApproveMemberReducer from "./approve_member_reducer";
import BanMemberReducer from "./ban_member_reducer";
import CreateHuddleReducer from "./create_huddle_reducer";
import CreateZoneReducer from "./create_zone_reducer";
import DeleteZoneReducer from "./delete_zone_reducer";
import EnterPortalReducer from "./enter_portal_reducer";
import JoinReducer from "./join_reducer";
import JoinHuddleReducer from "./join_huddle_reducer";
import LeaveHuddleReducer from "./leave_huddle_reducer";
import LogGroupRecordingReducer from "./log_group_recording_reducer";
import MoveZoneReducer from "./move_zone_reducer";
import RegisterGroupCallReducer from "./register_group_call_reducer";
import RejectMemberReducer from "./reject_member_reducer";
import SendAnnouncementReducer from "./send_announcement_reducer";
import SendChatMessageReducer from "./send_chat_message_reducer";
import SendDmReducer from "./send_dm_reducer";
import SendReactionReducer from "./send_reaction_reducer";
import SetAvailabilityReducer from "./set_availability_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";
import SetGuestsAllowedReducer from "./set_guests_allowed_reducer";
import SetStatusTextReducer from "./set_status_text_reducer";
import SubmitInputsReducer from "./submit_inputs_reducer";
import UnbanMemberReducer from "./unban_member_reducer";
import UpdateZoneReducer from "./update_zone_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import CallRecordingRow from "./call_recording_table";
import ChatMessageRow from "./chat_message_table";
import ConversationGroupRow from "./conversation_group_table";
import DmMessageRow from "./dm_message_table";
import GroupCallRow from "./group_call_table";
import GroupMemberRow from "./group_member_table";
import PlayerRow from "./player_table";
import PlayerNameRow from "./player_name_table";
import PlayerStatusRow from "./player_status_table";
import ReactionRow from "./reaction_table";
import SpaceMemberRow from "./space_member_table";
import SpaceSettingRow from "./space_setting_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  callRecording: __table({
    name: 'call_recording',
    indexes: [
      { accessor: 'id', name: 'call_recording_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'call_recording_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CallRecordingRow),
  chatMessage: __table({
    name: 'chat_message',
    indexes: [
      { accessor: 'id', name: 'chat_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'scope', name: 'chat_message_scope_idx_btree', algorithm: 'btree', columns: [
        'scope',
      ] },
      { accessor: 'target', name: 'chat_message_target_idx_btree', algorithm: 'btree', columns: [
        'target',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  conversationGroup: __table({
    name: 'conversation_group',
    indexes: [
      { accessor: 'id', name: 'conversation_group_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'mapId', name: 'conversation_group_map_id_idx_btree', algorithm: 'btree', columns: [
        'mapId',
      ] },
    ],
    constraints: [
      { name: 'conversation_group_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConversationGroupRow),
  dmMessage: __table({
    name: 'dm_message',
    indexes: [
      { accessor: 'id', name: 'dm_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'recipient', name: 'dm_message_recipient_idx_btree', algorithm: 'btree', columns: [
        'recipient',
      ] },
      { accessor: 'sender', name: 'dm_message_sender_idx_btree', algorithm: 'btree', columns: [
        'sender',
      ] },
    ],
    constraints: [
      { name: 'dm_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DmMessageRow),
  groupCall: __table({
    name: 'group_call',
    indexes: [
      { accessor: 'groupId', name: 'group_call_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
    ],
    constraints: [
      { name: 'group_call_group_id_key', constraint: 'unique', columns: ['groupId'] },
    ],
  }, GroupCallRow),
  groupMember: __table({
    name: 'group_member',
    indexes: [
      { accessor: 'groupId', name: 'group_member_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { accessor: 'identity', name: 'group_member_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'group_member_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, GroupMemberRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'mapId', name: 'player_map_id_idx_btree', algorithm: 'btree', columns: [
        'mapId',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  playerName: __table({
    name: 'player_name',
    indexes: [
      { accessor: 'identity', name: 'player_name_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_name_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerNameRow),
  playerStatus: __table({
    name: 'player_status',
    indexes: [
      { accessor: 'identity', name: 'player_status_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_status_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerStatusRow),
  reaction: __table({
    name: 'reaction',
    indexes: [
      { accessor: 'identity', name: 'reaction_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'reaction_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ReactionRow),
  spaceMember: __table({
    name: 'space_member',
    indexes: [
      { accessor: 'identity', name: 'space_member_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'space_member_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, SpaceMemberRow),
  spaceSetting: __table({
    name: 'space_setting',
    indexes: [
      { accessor: 'id', name: 'space_setting_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'space_setting_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpaceSettingRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("announce_idle_suspend", AnnounceIdleSuspendReducer),
  __reducerSchema("apply_for_membership", ApplyForMembershipReducer),
  __reducerSchema("approve_member", ApproveMemberReducer),
  __reducerSchema("ban_member", BanMemberReducer),
  __reducerSchema("create_huddle", CreateHuddleReducer),
  __reducerSchema("create_zone", CreateZoneReducer),
  __reducerSchema("delete_zone", DeleteZoneReducer),
  __reducerSchema("enter_portal", EnterPortalReducer),
  __reducerSchema("join", JoinReducer),
  __reducerSchema("join_huddle", JoinHuddleReducer),
  __reducerSchema("leave_huddle", LeaveHuddleReducer),
  __reducerSchema("log_group_recording", LogGroupRecordingReducer),
  __reducerSchema("move_zone", MoveZoneReducer),
  __reducerSchema("register_group_call", RegisterGroupCallReducer),
  __reducerSchema("reject_member", RejectMemberReducer),
  __reducerSchema("send_announcement", SendAnnouncementReducer),
  __reducerSchema("send_chat_message", SendChatMessageReducer),
  __reducerSchema("send_dm", SendDmReducer),
  __reducerSchema("send_reaction", SendReactionReducer),
  __reducerSchema("set_availability", SetAvailabilityReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("set_guests_allowed", SetGuestsAllowedReducer),
  __reducerSchema("set_status_text", SetStatusTextReducer),
  __reducerSchema("submit_inputs", SubmitInputsReducer),
  __reducerSchema("unban_member", UnbanMemberReducer),
  __reducerSchema("update_zone", UpdateZoneReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.7.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

