// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey().autoInc(),
  kind: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  dir: __t.i8(),
  hp: __t.i32(),
  spawnIdx: __t.u16().name("spawn_idx"),
  respawnAt: __t.timestamp().name("respawn_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
