// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  facing: __t.i8(),
  onGround: __t.bool().name("on_ground"),
  rope: __t.i32(),
  tick: __t.u32(),
  online: __t.bool(),
  allowanceMicros: __t.i64().name("allowance_micros"),
  updatedAt: __t.timestamp().name("updated_at"),
});
