// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  id: __t.u64(),
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  facing: __t.i8(),
  onGround: __t.bool(),
  rope: __t.i32(),
  tick: __t.u32(),
  online: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PlayerGuard = __t.object("PlayerGuard", {
  identity: __t.identity(),
  allowanceMicros: __t.i64(),
});
export type PlayerGuard = __Infer<typeof PlayerGuard>;

export const PlayerName = __t.object("PlayerName", {
  identity: __t.identity(),
  name: __t.string(),
});
export type PlayerName = __Infer<typeof PlayerName>;

export const SpaceMember = __t.object("SpaceMember", {
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  status: __t.string(),
  role: __t.string(),
  requestedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SpaceMember = __Infer<typeof SpaceMember>;

export const SpaceSetting = __t.object("SpaceSetting", {
  id: __t.u8(),
  guestsAllowed: __t.bool(),
});
export type SpaceSetting = __Infer<typeof SpaceSetting>;

