// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  id: __t.u64(),
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const ChatGuard = __t.object("ChatGuard", {
  identity: __t.identity(),
  allowanceMicros: __t.i64(),
});
export type ChatGuard = __Infer<typeof ChatGuard>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  senderName: __t.string(),
  text: __t.string(),
  sentAt: __t.timestamp(),
  scope: __t.string(),
  target: __t.u64(),
  announcement: __t.bool(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ConnectionEvent = __t.object("ConnectionEvent", {
  id: __t.u64(),
  identity: __t.identity(),
  connectionId: __t.connectionId(),
  kind: __t.string(),
  detail: __t.string(),
  at: __t.timestamp(),
});
export type ConnectionEvent = __Infer<typeof ConnectionEvent>;

export const ConversationGroup = __t.object("ConversationGroup", {
  id: __t.u64(),
  kind: __t.string(),
  name: __t.string(),
  closed: __t.bool(),
  mapId: __t.u32(),
  x: __t.f64(),
  y: __t.f64(),
  w: __t.f64(),
  h: __t.f64(),
});
export type ConversationGroup = __Infer<typeof ConversationGroup>;

export const DisconnectIntent = __t.object("DisconnectIntent", {
  connectionId: __t.connectionId(),
  announcedAt: __t.timestamp(),
});
export type DisconnectIntent = __Infer<typeof DisconnectIntent>;

export const DmMessage = __t.object("DmMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  recipient: __t.identity(),
  senderName: __t.string(),
  recipientName: __t.string(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type DmMessage = __Infer<typeof DmMessage>;

export const GroupMember = __t.object("GroupMember", {
  identity: __t.identity(),
  groupId: __t.u64(),
});
export type GroupMember = __Infer<typeof GroupMember>;

export const HuddleGuard = __t.object("HuddleGuard", {
  identity: __t.identity(),
  allowanceMicros: __t.i64(),
});
export type HuddleGuard = __Infer<typeof HuddleGuard>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  facing: __t.i8(),
  onGround: __t.bool(),
  rope: __t.i32(),
  tick: __t.u32(),
  online: __t.bool(),
  updatedAt: __t.timestamp(),
  mapId: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const PlayerGuard = __t.object("PlayerGuard", {
  identity: __t.identity(),
  allowanceMicros: __t.i64(),
});
export type PlayerGuard = __Infer<typeof PlayerGuard>;

export const PlayerName = __t.object("PlayerName", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
});
export type PlayerName = __Infer<typeof PlayerName>;

export const PlayerStatus = __t.object("PlayerStatus", {
  identity: __t.identity(),
  availability: __t.string(),
  text: __t.string(),
});
export type PlayerStatus = __Infer<typeof PlayerStatus>;

export const PortalGuard = __t.object("PortalGuard", {
  identity: __t.identity(),
  allowanceMicros: __t.i64(),
});
export type PortalGuard = __Infer<typeof PortalGuard>;

export const Reaction = __t.object("Reaction", {
  identity: __t.identity(),
  emoji: __t.string(),
  sentAt: __t.timestamp(),
});
export type Reaction = __Infer<typeof Reaction>;

export const ReactionGuard = __t.object("ReactionGuard", {
  identity: __t.identity(),
  allowanceMicros: __t.i64(),
});
export type ReactionGuard = __Infer<typeof ReactionGuard>;

export const SpaceMember = __t.object("SpaceMember", {
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  status: __t.string(),
  role: __t.string(),
  requestedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SpaceMember = __Infer<typeof SpaceMember>;

export const SpaceSetting = __t.object("SpaceSetting", {
  id: __t.u8(),
  guestsAllowed: __t.bool(),
});
export type SpaceSetting = __Infer<typeof SpaceSetting>;

export const StatusGuard = __t.object("StatusGuard", {
  identity: __t.identity(),
  allowanceMicros: __t.i64(),
});
export type StatusGuard = __Infer<typeof StatusGuard>;

