// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  secret: __t.string(),
  recordingId: __t.string(),
  meetingId: __t.string(),
  status: __t.string(),
  objectKey: __t.string(),
  outputFileName: __t.string(),
  startedAtMs: __t.u64(),
  durationSecs: __t.u32(),
};
