// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AnnounceIdleSuspendReducer from "../announce_idle_suspend_reducer";
import ApplyForMembershipReducer from "../apply_for_membership_reducer";
import ApproveMemberReducer from "../approve_member_reducer";
import BanMemberReducer from "../ban_member_reducer";
import CreateHuddleReducer from "../create_huddle_reducer";
import CreateZoneReducer from "../create_zone_reducer";
import DeleteZoneReducer from "../delete_zone_reducer";
import EnterPortalReducer from "../enter_portal_reducer";
import JoinReducer from "../join_reducer";
import JoinHuddleReducer from "../join_huddle_reducer";
import LeaveHuddleReducer from "../leave_huddle_reducer";
import MoveZoneReducer from "../move_zone_reducer";
import PlayGestureReducer from "../play_gesture_reducer";
import RejectMemberReducer from "../reject_member_reducer";
import SendAnnouncementReducer from "../send_announcement_reducer";
import SendChatMessageReducer from "../send_chat_message_reducer";
import SendDmReducer from "../send_dm_reducer";
import SendReactionReducer from "../send_reaction_reducer";
import SetAvailabilityReducer from "../set_availability_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import SetGuestsAllowedReducer from "../set_guests_allowed_reducer";
import SetStatusTextReducer from "../set_status_text_reducer";
import SubmitInputsReducer from "../submit_inputs_reducer";
import UnbanMemberReducer from "../unban_member_reducer";
import UpdateZoneReducer from "../update_zone_reducer";

export type AnnounceIdleSuspendParams = __Infer<typeof AnnounceIdleSuspendReducer>;
export type ApplyForMembershipParams = __Infer<typeof ApplyForMembershipReducer>;
export type ApproveMemberParams = __Infer<typeof ApproveMemberReducer>;
export type BanMemberParams = __Infer<typeof BanMemberReducer>;
export type CreateHuddleParams = __Infer<typeof CreateHuddleReducer>;
export type CreateZoneParams = __Infer<typeof CreateZoneReducer>;
export type DeleteZoneParams = __Infer<typeof DeleteZoneReducer>;
export type EnterPortalParams = __Infer<typeof EnterPortalReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type JoinHuddleParams = __Infer<typeof JoinHuddleReducer>;
export type LeaveHuddleParams = __Infer<typeof LeaveHuddleReducer>;
export type MoveZoneParams = __Infer<typeof MoveZoneReducer>;
export type PlayGestureParams = __Infer<typeof PlayGestureReducer>;
export type RejectMemberParams = __Infer<typeof RejectMemberReducer>;
export type SendAnnouncementParams = __Infer<typeof SendAnnouncementReducer>;
export type SendChatMessageParams = __Infer<typeof SendChatMessageReducer>;
export type SendDmParams = __Infer<typeof SendDmReducer>;
export type SendReactionParams = __Infer<typeof SendReactionReducer>;
export type SetAvailabilityParams = __Infer<typeof SetAvailabilityReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type SetGuestsAllowedParams = __Infer<typeof SetGuestsAllowedReducer>;
export type SetStatusTextParams = __Infer<typeof SetStatusTextReducer>;
export type SubmitInputsParams = __Infer<typeof SubmitInputsReducer>;
export type UnbanMemberParams = __Infer<typeof UnbanMemberReducer>;
export type UpdateZoneParams = __Infer<typeof UpdateZoneReducer>;

