// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApproveMemberReducer from "../approve_member_reducer";
import JoinReducer from "../join_reducer";
import RemoveMemberReducer from "../remove_member_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import SetGuestsAllowedReducer from "../set_guests_allowed_reducer";
import SubmitInputsReducer from "../submit_inputs_reducer";

export type ApproveMemberParams = __Infer<typeof ApproveMemberReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type RemoveMemberParams = __Infer<typeof RemoveMemberReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type SetGuestsAllowedParams = __Infer<typeof SetGuestsAllowedReducer>;
export type SubmitInputsParams = __Infer<typeof SubmitInputsReducer>;

